import CommunicationClosure.Protocols.RaftWithHistory

/-!
A network-bearing version of the history-bearing Raft model.

The earlier history model records receive events, but it does not model the
communication medium.  This wrapper adds an explicit set of in-flight messages.
Receive steps require the concrete message to be present in the pre-state
network and remove it from the post-state network.  A separate `send` step adds
an arbitrary message to the network without changing Raft state; this keeps the
network model explicit without pretending the current Raft state model exposes
the full broadcast/send logic of the TLA+ specification.
-/

universe u v

namespace CommunicationClosure.Protocols.RaftWithHistoryAndNetwork

open Classical

noncomputable section

abbrev Params := CommunicationClosure.Protocols.Raft.Params
abbrev Entry := CommunicationClosure.Protocols.Raft.Entry
abbrev Message := CommunicationClosure.Protocols.Raft.Message
abbrev Event := CommunicationClosure.Protocols.RaftWithHistory.Event
abbrev History := CommunicationClosure.Protocols.RaftWithHistory.History

/-- An explicit set of in-flight messages. -/
abbrev Network (p : Params) := Message p → Prop

namespace Network

variable {p : Params}

/-- The empty network. -/
def empty : Network p :=
  fun _ => False

/-- The post-network preserves exactly the pre-network. -/
def Preserves (net net' : Network p) : Prop :=
  net' = net

/-- The post-network adds one message. -/
def Adds (msg : Message p) (net net' : Network p) : Prop :=
  net' = fun msg' => net msg' ∨ msg' = msg

/-- The post-network removes one message that was in flight. -/
def Consumes (msg : Message p) (net net' : Network p) : Prop :=
  net msg ∧ net' = fun msg' => net msg' ∧ msg' ≠ msg

end Network

/-- Mutable Raft state plus ghost history plus explicit in-flight messages. -/
structure State (p : Params) where
  raft : CommunicationClosure.Protocols.Raft.State p
  history : History p
  network : Network p

namespace State

variable {p : Params}

/-- Initial network-bearing Raft state. -/
def init (p : Params) : State p where
  raft := CommunicationClosure.Protocols.Raft.State.init p
  history := CommunicationClosure.Protocols.RaftWithHistory.History.init
  network := Network.empty

def IsInit (s : State p) : Prop :=
  s = init p

end State

namespace Action

variable {p : Params} [DecidableEq p.Server]

def timeoutEvent (i : p.Server) (s s' : State p) : Event p :=
  CommunicationClosure.Protocols.RaftWithHistory.Event.timeout
    i (s.raft.currentTerm i) (s'.raft.currentTerm i)

def becomeLeaderEvent (i : p.Server) (s s' : State p) : Event p :=
  CommunicationClosure.Protocols.RaftWithHistory.Event.becameLeader
    i (s.raft.currentTerm i) (s.raft.log i) (s'.raft.log i)

def clientRequestEvent (i : p.Server) (v : p.Value) (s s' : State p) : Event p :=
  CommunicationClosure.Protocols.RaftWithHistory.Event.clientRequest
    i (s.raft.currentTerm i) v (s.raft.log i) (s'.raft.log i)

def advanceCommitIndexEvent (i : p.Server) (s s' : State p) : Event p :=
  CommunicationClosure.Protocols.RaftWithHistory.Event.commitAdvanced
    i (s.raft.currentTerm i)
    (s.raft.commitIndex i) (s'.raft.commitIndex i)

def receiveEvent (msg : Message p) (dest : p.Server) (s s' : State p) : Event p :=
  CommunicationClosure.Protocols.RaftWithHistory.Event.received msg dest
    (s.raft.currentTerm dest) (s'.raft.currentTerm dest)
    (s.raft.log dest) (s'.raft.log dest)

/-- The history update required by one wrapped base action. -/
def Records (event : Event p) (s s' : State p) : Prop :=
  s'.history = s.history.record event

/-- A pure network send: add an in-flight message without changing Raft state. -/
def send (msg : Message p) (s s' : State p) : Prop :=
  s'.raft = s.raft ∧
    s'.history = s.history ∧
    Network.Adds msg s.network s'.network

/--
The one-step transition relation generated by Raft actions plus explicit
network send/receive behavior.
-/
inductive Step (s s' : State p) : Prop where
  | send (msg : Message p) :
      send msg s s' →
      Step s s'
  | becomeLeader (i : p.Server) :
      p.InServer i →
      CommunicationClosure.Protocols.Raft.Action.becomeLeader i s.raft s'.raft →
      Records (becomeLeaderEvent i s s') s s' →
      Network.Preserves s.network s'.network →
      Step s s'
  | clientRequest (i : p.Server) (v : p.Value) :
      p.InServer i →
      CommunicationClosure.Protocols.Raft.Action.clientRequest i v s.raft s'.raft →
      Records (clientRequestEvent i v s s') s s' →
      Network.Preserves s.network s'.network →
      Step s s'
  | advanceCommitIndex (i : p.Server) :
      p.InServer i →
      CommunicationClosure.Protocols.Raft.Action.advanceCommitIndex i s.raft s'.raft →
      Records (advanceCommitIndexEvent i s s') s s' →
      Network.Preserves s.network s'.network →
      Step s s'
  | timeout (i : p.Server) :
      p.InServer i →
      CommunicationClosure.Protocols.Raft.Action.timeout i s.raft s'.raft →
      Records (timeoutEvent i s s') s s' →
      Network.Preserves s.network s'.network →
      Step s s'
  | receiveRequestVoteRequest
      (term lastLogTerm lastLogIndex : Nat) (source dest : p.Server) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleRequestVoteRequest
          dest source term lastLogTerm lastLogIndex s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.requestVoteRequest
            term lastLogTerm lastLogIndex source dest)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.requestVoteRequest
          term lastLogTerm lastLogIndex source dest)
        s.network s'.network →
      Step s s'
  | receiveRequestVoteResponse
      (term : Nat) (voteGranted : Bool) (log : List (Entry p))
      (source dest : p.Server) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.dropStaleResponse dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleRequestVoteResponse
          dest source term voteGranted s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.requestVoteResponse
            term voteGranted log source dest)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.requestVoteResponse
          term voteGranted log source dest)
        s.network s'.network →
      Step s s'
  | receiveAppendEntriesRequest
      (term prevLogIndex prevLogTerm : Nat) (entries : List (Entry p))
      (commitIndex : Nat) (source dest : p.Server) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleAppendEntriesRequest
          dest source term prevLogIndex prevLogTerm entries commitIndex
          s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.appendEntriesRequest
            term prevLogIndex prevLogTerm entries commitIndex source dest)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.appendEntriesRequest
          term prevLogIndex prevLogTerm entries commitIndex source dest)
        s.network s'.network →
      Step s s'
  | receiveAppendEntriesResponse
      (term : Nat) (success : Bool) (matchIndex : Nat)
      (source dest : p.Server) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.dropStaleResponse dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleAppendEntriesResponse
          dest source term matchIndex success s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.appendEntriesResponse
            term success matchIndex source dest)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.appendEntriesResponse
          term success matchIndex source dest)
        s.network s'.network →
      Step s s'
  | receiveCatchupRequest
      (term logLen : Nat) (entries : List (Entry p)) (commitIndex : Nat)
      (source dest : p.Server) (rounds : Nat) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleCatchupRequest
          dest source term logLen entries commitIndex rounds s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.catchupRequest
            term logLen entries commitIndex source dest rounds)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.catchupRequest
          term logLen entries commitIndex source dest rounds)
        s.network s'.network →
      Step s s'
  | receiveCatchupResponse
      (term : Nat) (success : Bool) (matchIndex : Nat)
      (source dest : p.Server) (roundsLeft : Nat) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleCatchupResponse
          dest source term matchIndex roundsLeft success s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.catchupResponse
            term success matchIndex source dest roundsLeft)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.catchupResponse
          term success matchIndex source dest roundsLeft)
        s.network s'.network →
      Step s s'
  | receiveCheckOldConfig
      (term : Nat) (add : Bool) (server source dest : p.Server) :
      (CommunicationClosure.Protocols.Raft.Action.updateTerm dest term s.raft s'.raft ∨
        CommunicationClosure.Protocols.Raft.Action.handleCheckOldConfig
          dest term add server s.raft s'.raft) →
      Records
        (receiveEvent
          (CommunicationClosure.Protocols.Raft.Message.checkOldConfig
            term add server source dest)
          dest s s')
        s s' →
      Network.Consumes
        (CommunicationClosure.Protocols.Raft.Message.checkOldConfig
          term add server source dest)
        s.network s'.network →
      Step s s'

end Action

/-- Reachability from the initial state under zero or more network-bearing steps. -/
inductive Reachable {p : Params} [DecidableEq p.Server] : State p → Prop where
  | init : Reachable (State.init p)
  | step {s s' : State p} :
      Reachable s → Action.Step s s' → Reachable s'

end

end CommunicationClosure.Protocols.RaftWithHistoryAndNetwork
